# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/SemanticKITTI_Tools',
                'doc_host': 'https://AIR-UFG.github.io',
                'git_url': 'https://github.com/AIR-UFG/SemanticKITTI_Tools',
                'lib_path': 'SemanticKITTI_Tools'},
  'syms': {'SemanticKITTI_Tools.core': {'SemanticKITTI_Tools.core.foo': ('core.html#foo', 'SemanticKITTI_Tools/core.py')}}}
